# region board
BOARD_SIZE = 32
BOARD_SHAPE = (BOARD_SIZE, BOARD_SIZE)
# endregion

# region neural network
AUGMENTATIONS=True
TRAIN_MODE = "Train"
TEST_MODE = "Test"
RANDOM_SEED = 1
DEPTH = 2
WIDTH_LAYER_1 = BOARD_SIZE * BOARD_SIZE
WIDTH_LAYER_2 = 512
WIDTH_LAYER_3 = 128
# endregion

# region Thresholds
OSCILLATOR_PREDICTION_THRESHOLD = 0.5
# endregion
