import os.path

DATA_SOURCES_PATH = "data-sources"
OSCILLATORS = "oscillators"
NON_OSCILLATORS = "non_oscillators"
OSCILLATORS_PATH = os.path.join(DATA_SOURCES_PATH, OSCILLATORS)
NON_OSCILLATORS_PATH = os.path.join(DATA_SOURCES_PATH, NON_OSCILLATORS)